"""Agregar tabla Empresa y relación empresa_id en Sale

Revision ID: 9210969f4952
Revises: 9cef934677c0
Create Date: 2025-06-28 09:25:47.036242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9210969f4952'
down_revision = '9cef934677c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('timbrado_numero', sa.String(length=20), nullable=False),
    sa.Column('timbrado_vigencia_desde', sa.Date(), nullable=False),
    sa.Column('timbrado_vigencia_hasta', sa.Date(), nullable=False),
    sa.Column('establecimiento', sa.String(length=3), nullable=False),
    sa.Column('punto_expedicion', sa.String(length=3), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sale_condition', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('establishment', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('issue_point', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('document_number', sa.String(length=7), nullable=False))
        batch_op.add_column(sa.Column('timbrado_numero', sa.String(length=20), nullable=False))
        batch_op.drop_constraint(batch_op.f('sales_invoice_number_key'), type_='unique')
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('sales_invoice_number_key'), ['invoice_number'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('timbrado_numero')
        batch_op.drop_column('document_number')
        batch_op.drop_column('issue_point')
        batch_op.drop_column('establishment')
        batch_op.drop_column('currency')
        batch_op.drop_column('sale_condition')
        batch_op.drop_column('empresa_id')

    op.drop_table('empresa')
    # ### end Alembic commands ###
